In [79]:
import pandas as pd
import numpy as np
import random

In [80]:
df_base = pd.read_csv('BASE202010.csv', low_memory = False, index_col=[0])

In [55]:
df_base[df_base.MRR_REV == 0]

,TENURE_GRP,ACCOUNT_TYPE,ACCOUNT_SUB_TYPE,BAN_REGION,RVP_REGION,ACCOUNT_ID,SE_FLAG,INIT_ACT_YYMM,PLAN_TYPE,PPLAN_SERIES_TYPE,...,MOU_OUT,MOU_LOCAL,MOU_LD,MOU_LD_CAN,MOU_LD_USA,MOU_LD_INTL,DATA_MB,SMS_OC,LINES,MSF_PER_LINE
11,a ) 0,B,M,AB,AB/MW,1796,0,2020-09-14,Data Only,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN
13,a ) 0,B,M,AB,AB/MW,2045,0,2020-09-01,Data Only,5,...,0.0,0.0,0.0,0.0,0.0,0.0,86241.0,0.0,1,70.00
152,a ) 0,B,M,AB,AB/MW,6774,0,2020-09-09,Data Only,5,...,0.0,0.0,0.0,0.0,0.0,0.0,4.0,2.0,1,35.00
154,a ) 0,B,M,AB,AB/MW,7757,0,2020-09-14,Data Only,5,...,0.0,0.0,0.0,0.0,0.0,0.0,73.0,0.0,1,10.00
368,a ) 0,B,M,AB,ON (CSS),7400,0,2020-09-17,Voice & Voice and Data,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
624457,j ) 60 +,G,P,SW,ON (SWO/SMB),9743,0,2004-10-15,Voice & Voice and Data,1,...,460.0,899.0,52.0,52.0,0.0,0.0,4497.0,654.0,1,48.40
625532,j ) 60 +,G,P,SW,ON (SWO/SMB),10624,0,2011-04-06,Data Only,5,...,0.0,0.0,0.0,0.0,0.0,0.0,3693.0,0.0,1,14.30
625734,j ) 60 +,G,P,SW,Other,9280,0,2011-04-28,Voice & Voice and Data,1,...,84.0,66.0,174.0,174.0,0.0,0.0,222.0,24.0,1,20.25
625736,j ) 60 +,G,P,SW,Other,9280,0,2014-05-27,Data Only,5,...,0.0,0.0,0.0,0.0,0.0,0.0,5261.0,0.0,1,45.00
625766,j ) 60 +,G,P,SW,QC/Ottawa,5423,0,2015-06-19,Data Only,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,5.00

In [74]:
#Here we add a random fluctuation on 4 columns,
#note that the fluctuation of REV columns do not
#corelate with the DATA_MB

#Just for demonstration purpose

def new_fake(df, columns):
    rand = np.array([random.uniform(0.8,1.2) for i in range(df_base.shape[0])])
    for column in columns:
        df[column] = df[column] * rand
    new_df = df.iloc[np.random.randint(625776, size=625000)]
    return new_df

In [75]:
a = new_fake(df_base, ['MRR_REV', 'TOTAL_REV', 'MSF_REV', 'DATA_MB'])

In [76]:
for i in range(2,10):
    s = 'BASE_20200' + str(i) + '.csv'
    fake_df = new_fake(df_base, ['MRR_REV', 'TOTAL_REV', 'MSF_REV', 'DATA_MB'])
    fake_df.to_csv(s, index=False)

In [77]:
for i in range(10,13):
    s = 'BASE_2020' + str(i) + '.csv'
    fake_df = new_fake(df_base, ['MRR_REV', 'TOTAL_REV', 'MSF_REV', 'DATA_MB'])
    fake_df.to_csv(s, index=False)

In [78]:
for i in range(1,3):
    s = 'BASE_20210' + str(i) + '.csv'
    fake_df = new_fake(df_base, ['MRR_REV', 'TOTAL_REV', 'MSF_REV', 'DATA_MB'])
    fake_df.to_csv(s, index=False)

In [ ]:
new_df = df.iloc[np.random.randint(625776, size=625000)]